openapi: 3.0.3
info:
  title: Student Management API
  description: API for managing student records
  version: 1.0.0
servers:
  - url: /students
    description: Student Management Server
paths:
  /health:
    get:
      description: Health check endpoint for Student Management API
      operationId: healthCheck
      tags:
        - health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
        '500':
          $ref: '#/components/responses/InternalServerError'
          
  /graphql:
    get:
      summary: Endpoint GraphQL para consultar estudiantes (GET)
      operationId: graphqlQueryGet
      tags:
        - graphql
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
          description: Consulta GraphQL a ejecutar
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    description: Datos de la respuesta
                    type: object
                    additionalProperties: true
        '400':
          description: Error de solicitud
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          $ref: '#/components/responses/InternalServerError'
paths:
  /graphql:
    get:
      summary: GraphQL endpoint to query students (GET)
      operationId: graphqlQueryGet
      tags:
        - graphql
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
          description: GraphQL query to execute
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
        '400':
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          $ref: '#/components/responses/InternalServerError'               
  /:
    get:
      summary: Get all students
      responses:
        '200':
          description: A list of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
    post:
      summary: Create a new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '201':
          description: Student created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
  /{id}:
    parameters:
      - in: path
        name: id
        required: true
        description: ID of the student
        schema:
          type: string
          pattern: ^[a-f\d]+$
    get:
      summary: Get a student by ID
      responses:
        '200':
          description: Student details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
    put:
      summary: Update a student by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Student updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
    delete:
      summary: Delete a student by ID
      responses:
        '204':
          description: Student deleted successfully
  /{id}/signUp/{courseId}:
    parameters:
      - in: path
        name: id
        required: true
        description: ID of the student
        schema:
          type: string
          pattern: ^[a-f\d]+$
      - in: path
        name: courseId
        required: true
        description: ID of the course to be signed in
        schema:
          type: string
          pattern: ^[a-f\d]+$
    post:
      summary: Sign up for a course
      responses:
        '200':
          description: Sign up to specific Course
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignUpResult'
    delete:
      summary: Delete signed up course
      responses:
        '200':
          description: Delete signed up course
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignUpResult'
components:
  schemas:
    ErrorModel:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    HealthStatus:
      description: Health check status
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          enum:
            - OK
        timestamp:
          type: integer
          description: Milliseconds since Epoch time
    Student:
      type: object
      properties:
        id:
          type: string
          pattern: ^[a-f\d]+$
          description: Unique identifier for the student
        documentId:
          type: string
          description: Document id like passport, dni, other of the student
        name:
          type: string
          description: Name of the student
        age:
          type: integer
          description: Age of the student
        email:
          type: string
          format: email
          description: Email address of the student
      parent:
          type: object
          properties:
            id:
              type: string
              pattern: ^[a-f\d]+$
              description: Unique identifier for the parent
            name:
              type: string
              description: Name of the parent
            email:
              type: string
              format: email
              description: Email address of the parent
            documentId:
              type: string
              description: Document id like passport, dni, other of the parent
          nullable: true
      courses:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                pattern: ^[a-f\d]+$
                description: Unique identifier for the course
              name:
                type: string
                description: Name of the course
              progress: 
                type: integer
                description: Progress of the student in the course using %
          description: List of courses the student is enrolled in
      required:
        - name
        - documentId
        - age
        - email
    SignUpCommand:
      description: Sign up to course command
      type: object
      required:
        - courseId
      properties:
        courseId:
          type: string
          pattern: ^[a-f\d]+$
          description: Unique ID of the course to be signed up
    SignUpResult:
      description: Sign up result
      allOf:
        - $ref: '#/components/schemas/SignUpCommand'
        - type: object
          required:
            - id
            - timestamp
          properties:
            id:
              type: string
              pattern: ^[a-f\d]+$
              description: Unique ID of the course signed up
            result:
              type: number
            message:
              type: string
            timestamp:
              type: integer
              description: Milliseconds since Epoch time
  responses:
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
    NotFoundError:
      description: Not found error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
  requestBodies:
    SignUpCommand:
      description: Sign up to course command request body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SignUpCommand'
tags:
  - name: health
    description: health check